#!/bin/bash

# Motosai Deployment Script
# This script sets up and deploys the Motosai application to Google Cloud Platform

set -e

echo "🏍️ Motosai Deployment Script"
echo "============================"

# Configuration
PROJECT_ID="punchies-game"  # Using same project as Punchies
REGION="us-central1"
BUCKET_NAME="motosai-app"
REPOSITORY_NAME="motosai-repo"

echo "Using project: $PROJECT_ID"
echo ""

# Step 1: Set the project
echo "1. Setting active project..."
gcloud config set project $PROJECT_ID

# Step 2: Enable required APIs
echo ""
echo "2. Enabling required Google Cloud APIs..."
gcloud services enable cloudbuild.googleapis.com \
    run.googleapis.com \
    artifactregistry.googleapis.com \
    storage.googleapis.com

# Step 3: Create Cloud Storage bucket for frontend
echo ""
echo "3. Creating Cloud Storage bucket for frontend..."
if gsutil ls -b gs://$BUCKET_NAME &>/dev/null; then
    echo "   Bucket gs://$BUCKET_NAME already exists"
else
    gsutil mb -l $REGION gs://$BUCKET_NAME
    echo "   Created bucket gs://$BUCKET_NAME"
fi

# Make bucket publicly readable
echo "   Setting bucket permissions..."
gsutil iam ch allUsers:objectViewer gs://$BUCKET_NAME

# Step 4: Create Artifact Registry repository for Docker images
echo ""
echo "4. Creating Artifact Registry repository..."
if gcloud artifacts repositories describe $REPOSITORY_NAME --location=$REGION &>/dev/null; then
    echo "   Repository $REPOSITORY_NAME already exists"
else
    gcloud artifacts repositories create $REPOSITORY_NAME \
        --repository-format=docker \
        --location=$REGION \
        --description="Docker repository for Motosai"
    echo "   Created repository $REPOSITORY_NAME"
fi

# Step 5: Configure Docker authentication
echo ""
echo "5. Configuring Docker authentication..."
gcloud auth configure-docker ${REGION}-docker.pkg.dev

# Step 6: Submit build to Cloud Build
echo ""
echo "6. Starting Cloud Build deployment..."
echo "   This will build and deploy both server and client"

cd /Users/fromastermarv/Documents/Codeyard/motosai

gcloud builds submit --config cloudbuild.yaml \
    --substitutions=_PROJECT_ID=$PROJECT_ID

# Step 7: Get the deployed Cloud Run service URL
echo ""
echo "7. Getting deployed service URL..."
SERVICE_URL=$(gcloud run services describe motosai-websocket \
    --region=$REGION \
    --format='value(status.url)')

if [ -z "$SERVICE_URL" ]; then
    echo "   ⚠️  Could not retrieve Cloud Run service URL"
    echo "   Please check Cloud Console for the actual URL"
else
    echo "   Cloud Run Service URL: $SERVICE_URL"
    
    # Step 8: Update client production environment file
    echo ""
    echo "8. Updating client production environment..."
    cat > client/.env.production <<EOF
# Auto-generated by deploy.sh
VITE_SERVER_URL=$SERVICE_URL
EOF
    echo "   Updated client/.env.production with server URL"
    
    # Step 9: Rebuild and redeploy client with correct server URL
    echo ""
    echo "9. Rebuilding client with production server URL..."
    cd client
    npm run build
    
    echo "   Redeploying client to Cloud Storage..."
    gsutil -m rsync -r -d ./dist/ gs://$BUCKET_NAME/
    gsutil -m setmeta -h "Cache-Control:public, max-age=300" gs://$BUCKET_NAME/**.html
    gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" gs://$BUCKET_NAME/**-*.js
    gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" gs://$BUCKET_NAME/**-*.css
    cd ..
fi

# Final summary
echo ""
echo "====================================="
echo "✅ Deployment Complete!"
echo "====================================="
echo ""
echo "📱 Frontend URL:"
echo "   https://storage.googleapis.com/$BUCKET_NAME/index.html"
echo ""
if [ ! -z "$SERVICE_URL" ]; then
    echo "🖥️  Backend URL:"
    echo "   $SERVICE_URL"
    echo ""
fi
echo "📊 View logs:"
echo "   gcloud logging read \"resource.type=cloud_run_revision AND resource.labels.service_name=motosai-websocket\" --limit 50"
echo ""
echo "🔍 View Cloud Run service:"
echo "   https://console.cloud.google.com/run/detail/$REGION/motosai-websocket/metrics?project=$PROJECT_ID"
echo ""