/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/fromastermarv/Documents/Codeyard/Motosai/client/public/models/sedan.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube006_3: THREE.Mesh
    Cube006_4: THREE.Mesh
    Cube006_5: THREE.Mesh
    Cube035: THREE.Mesh
    Cube035_1: THREE.Mesh
    Cube037: THREE.Mesh
    Cube037_1: THREE.Mesh
    Cube043: THREE.Mesh
    Cube043_1: THREE.Mesh
    Cube047: THREE.Mesh
    Cube047_1: THREE.Mesh
  }
  materials: {
    ['body grey']: THREE.MeshStandardMaterial
    ['body white']: THREE.MeshStandardMaterial
    windows: THREE.MeshStandardMaterial
    headlights: THREE.MeshStandardMaterial
    ['rear lights']: THREE.MeshStandardMaterial
    ['body black']: THREE.MeshStandardMaterial
    wheels: THREE.MeshStandardMaterial
    tires: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sedan.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.6, -1.52]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['body grey']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['body white']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.windows} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.headlights} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['rear lights']} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['body black']} />
      </group>
      <group position={[-1.027, 0.4, -3.129]}>
        <mesh geometry={nodes.Cube035.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.027, 0.4, 0.088]}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.027, 0.4, -3.129]}>
        <mesh geometry={nodes.Cube043.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.027, 0.4, 0.088]}>
        <mesh geometry={nodes.Cube047.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube047_1.geometry} material={materials.tires} />
      </group>
    </group>
  )
}

useGLTF.preload('/sedan.glb')
