/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/fromastermarv/Documents/Codeyard/Motosai/client/public/models/semi.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube006_3: THREE.Mesh
    Cube006_4: THREE.Mesh
    Cube006_5: THREE.Mesh
    Cube006_6: THREE.Mesh
    Cube082: THREE.Mesh
    Cube082_1: THREE.Mesh
    Cube083: THREE.Mesh
    Cube083_1: THREE.Mesh
    Cube084: THREE.Mesh
    Cube084_1: THREE.Mesh
    Cube085: THREE.Mesh
    Cube085_1: THREE.Mesh
    Cube086: THREE.Mesh
    Cube086_1: THREE.Mesh
    Cube087: THREE.Mesh
    Cube087_1: THREE.Mesh
    Cube088: THREE.Mesh
    Cube088_1: THREE.Mesh
    Cube089: THREE.Mesh
    Cube089_1: THREE.Mesh
    Cube090: THREE.Mesh
    Cube090_1: THREE.Mesh
    Cube091: THREE.Mesh
    Cube091_1: THREE.Mesh
    Cube092: THREE.Mesh
    Cube092_1: THREE.Mesh
    Cube093: THREE.Mesh
    Cube093_1: THREE.Mesh
  }
  materials: {
    ['body black']: THREE.MeshStandardMaterial
    ['body dark blue']: THREE.MeshStandardMaterial
    ['body white']: THREE.MeshStandardMaterial
    windows: THREE.MeshStandardMaterial
    headlights: THREE.MeshStandardMaterial
    ['rear lights']: THREE.MeshStandardMaterial
    ['body dark yellow']: THREE.MeshStandardMaterial
    wheels: THREE.MeshStandardMaterial
    tires: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/semi.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.6, -1.185]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['body black']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['body dark blue']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['body white']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials.windows} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials.headlights} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials['rear lights']} />
        <mesh geometry={nodes.Cube006_6.geometry} material={materials['body dark yellow']} />
      </group>
      <group position={[-1.288, 0.4, 0.421]}>
        <mesh geometry={nodes.Cube082.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube082_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.288, 0.4, -3.532]}>
        <mesh geometry={nodes.Cube083.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube083_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, 0.421]}>
        <mesh geometry={nodes.Cube084.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube084_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, -3.532]}>
        <mesh geometry={nodes.Cube085.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube085_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.288, 0.4, -2.392]}>
        <mesh geometry={nodes.Cube086.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube086_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, -2.392]}>
        <mesh geometry={nodes.Cube087.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube087_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.288, 0.4, -9.252]}>
        <mesh geometry={nodes.Cube088.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube088_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, -9.252]}>
        <mesh geometry={nodes.Cube089.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube089_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.288, 0.4, -10.392]}>
        <mesh geometry={nodes.Cube090.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube090_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, -10.392]}>
        <mesh geometry={nodes.Cube091.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube091_1.geometry} material={materials.tires} />
      </group>
      <group position={[-1.288, 0.4, -11.542]}>
        <mesh geometry={nodes.Cube092.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube092_1.geometry} material={materials.tires} />
      </group>
      <group position={[1.288, 0.4, -11.542]}>
        <mesh geometry={nodes.Cube093.geometry} material={materials.wheels} />
        <mesh geometry={nodes.Cube093_1.geometry} material={materials.tires} />
      </group>
    </group>
  )
}

useGLTF.preload('/semi.glb')
